### PR TITLE
Adding basics of tinygo and tamago (efi) support

### PR DESCRIPTION
**Pull request by andydotxyz**
Adding new embedded package to house helpful drivers for smaller hardware.

Work in progress as the Go version is not OK and the driver API can be polished a bit more

### CODE REVIEW

**Comment by rgl** [comment]
@andydotxyz is this ready to be merged to main? I'm curious about seeing this work on efi :)

**Comment by andydotxyz** [comment]
As above the code is already but I have not completed the documentation

**Comment by rgl** [comment]
@andydotxyz already in this pr? I mean, https://github.com/search?q=org%3Afyne-io%20NewUEFIDriver&type=code does not seem to find the new NewUEFIDriver function in a main branch.

**Comment by andydotxyz** [comment]
I don't understand what main branch you would expect to find that function on, as it is inside this PR which has not landed.

**Comment by rgl** [comment]
@andydotxyz sorry, I misunderstood as this had already landed on main. And only the docs were missing. I now understand the state of this.i will try branch. Thanks!

**Comment by rgl** [comment]
@andydotxyz I've tried to use this, but I'm stuck building it. Can you have a look at the https://github.com/rgl/fyne-uefi-playground/tree/wip README and go.mod? probably, I've mismatched the tomago/fyne versions.

It currently fails to build with the error: `link: duplicated definition of symbol runtime.ramStart, from github.com/usbarmory/tamago/amd64 (type SNOPTRDATA size 8) and github.com/usbarmory/go-boot/uefi/x64 (type SNOPTRDATA size 8)`, which, I'm not sure how to fix.

**Comment by andydotxyz** [comment]
Have you tried and/or succeeded to build the demo project that I have created? https://github.com/andydotxyz/presentations/tree/main/2025-08-27-GopherCon/demo

**Comment by rgl** [comment]
I tried with that demo, and it also failed, but with a different error:

```console
$ make noosdemo.efi
GOOS=tamago GOARCH=amd64 /opt/tamago-go/bin/go build -tags linkcpuinit,linkramsize,linkramstart,linkprintk,no_animations,release -trimpath -ldflags "-s -w -E cpuinit -T 268500992 -R 0x1000" -o noosdemo-tamago
# github.com/usbarmory/tamago/amd64
/home/vscode/go/pkg/mod/github.com/usbarmory/tamago@v0.0.0-20250506193353-852659b3a9d6/amd64/amd64.go:63:10: undefined: runtime.Idle
make: *** [Makefile:53: tamago] Error 1
```

I'm using tamago 1.24.2 as installed in the devcontainer at https://github.com/rgl/fyne-uefi-playground/blob/wip/.devcontainer/Dockerfile and described in https://github.com/rgl/fyne-uefi-playground/blob/wip/README.md.

**Comment by andydotxyz** [comment]
Idle was added in 1.24.3 (which is what I used in testing) so you'll either need to update the tamago or downgrade the requirement in the go.mod - it is a very delicate balance I'm afraid.

**Comment by rgl** [comment]
it worked with tamago 1.24.3! soon I'll try the actual .efi file :-)

thou, the demos `go.mod` `go 1.24.2` line should be updated to `go 1.24.3` to hint the user in which version to use.

**Comment by rgl** [comment]
although the demo is somewhat laggy, and after a while it crashes and burns, it was cute to see in qemu!

**Comment by andydotxyz** [comment]
There is optimisation work to be done for sure, often the way with first pass. It should not have crashed though - if you can add the details here it could be resolved before the PR lands...

**Comment by rgl** [comment]
here, with a 2G of memory VM, leaving it running for awhile (~30m), it crashes.

the exact instructions are described at https://github.com/rgl/fyne-uefi-playground/blob/wip/README.md
